version: '3.8'

services:
  backend:
    build: ./
      context: .
      args:
        store_type: "postgres"
    ports:
      - '8080:8080'
    container_name: server
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: fintechPostgres
    environment:
      POSTGRES_DB: "fintechDB"
      POSTGRES_USER: "fintechAdmin"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data2
